[tasks.PUBLISH]
description = "Build hoge"
script = [
    '''
#!/usr/bin/env fish
echo Publish this package to crate.io
cargo publish
''']
dependencies = ["bump"]


[tasks.bump]
description = ""
script = ['''
#!/usr/bin/env fish
echo Updating package version...

cargo bump $argv

echo package version became (cargo metadata --format-version=1 --no-deps | jq .packages[0].version | sed s/\"//g)
'''
]
dependencies = ["git"]


[tasks.git]
description = "Build hoge"
script = ['''
#!/usr/bin/env fish

git add Cargo.toml
git commit -m ":tada: Update package version"
git tag v(cargo metadata --format-version=1 --no-deps | jq .packages[0].version | sed s/\"//g)
git push origin v(cargo metadata --format-version=1 --no-deps | jq .packages[0].version | sed s/\"//g)
git push origin master
'''
]
